### ISSUE TITLE
No notification about incorrect credentials

### ISSUE THREAD

**Issue by Crash-1** [cloudflare/Cloudflare-CPanel#122]
Hello,
I've faced following strange behavior of plugin: 
In case if you enter incorrect access credentials you won't get any error message, as far as I can see this feature doesn't work since 6.0.8 version and till current 6.1.1.
in "developer console" of browser you will get following message:
"Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings."
Could you please check JS vars or such behavior is correct and I missed something?
![2017-01-13-130014_510x31_scrot](https://cloud.githubusercontent.com/assets/24790987/21927854/44f176ba-d990-11e6-90e0-83e98a145fda.png)

**Comment by jwineman** [comment]
Hi,

This is related to https://github.com/cloudflare/Cloudflare-CPanel/issues/119.  We're aware of the issue and hoping to have a fix by the end of next week.  I'll update this ticket when the release is out.

Thanks,
John

**Comment by jwineman** [comment]
Hi,

If you update to 6.1.2 is this still an issue?

Thanks,
John

**Comment by Crash-1** [comment]
Hi,
Yes seems everything is okay now.

But I've found another typo/mistake in response body in error_log of cPanel, should I post a new issue?

**Comment by thellimist** [comment]
A new issue would be better. Thanks.
