### ISSUE TITLE
Installation error: Missing file compiled.js.map

### ISSUE THREAD

**Issue by FabioWidmer** [cloudflare/Cloudflare-CPanel#125]
An error occurred during installation of version 6.1.2. The problem is the file compiled.js.map.
This file is not included in the latest version. Is it no longer required or just not included? Anyway you should add the file or remove the line of code in the installation script.

cloudflare.install.sh:
`install $SOURCE_DIR/compiled.js.map $INSTALL_DIR/base/frontend/paper_lantern/cloudflare`

**Comment by jwineman** [comment]
Thanks for reporting this!  Fixed in  https://github.com/cloudflare/Cloudflare-CPanel/pull/126.
