### ISSUE TITLE
"Cloudflare" branding reads as "CloudFlare" in cPanel

### ISSUE THREAD

**Issue by ronkh** [cloudflare/Cloudflare-CPanel#127]
cPanel 11.60.0.37
Cloudflare plugin v6.1.2

The Cloudflare option in the main page of cPanel has not had its branding text updated to `Cloudflare` yet. Currently, it still reads as `CloudFlare`, with the old capital `F`.

![image](https://cloud.githubusercontent.com/assets/2492319/23520008/b77d7f52-ff3e-11e6-8d92-ee379ad0a915.png)

After navigating to the Cloudflare page, the following pages' title does reflect the proper `Cloudflare` casing.

![image](https://cloud.githubusercontent.com/assets/2492319/23520075/04dd623a-ff3f-11e6-8333-e2842e53e0f3.png)

**Comment by jwineman** [comment]
Thanks for reporting this!  @thellimist think you can tackle this before the release or need me to do it?

**Comment by jwineman** [comment]
https://github.com/cloudflare/Cloudflare-CPanel/blob/master/installers/cloudflare_simple/install.json#L4

**Comment by thellimist** [comment]
Will do thanks

**Comment by thellimist** [comment]
https://github.com/cloudflare/Cloudflare-CPanel/pull/131
