### ISSUE TITLE
Make CPanelAPI.php PSR2 compliant 

### ISSUE THREAD

**Issue by jwineman** [cloudflare/Cloudflare-CPanel#129]
It has underscored method names.

**Comment by thellimist** [comment]
What is `CloudFlareAPI.php`?

**Comment by jwineman** [comment]
Sorry meant https://github.com/cloudflare/Cloudflare-CPanel/blob/master/src/Cpanel/CpanelAPI.php

Its a big refactor cause lots of the methods are snake case.

**Comment by thellimist** [comment]
Need to test the changes made in #146.
