### ISSUE TITLE
Paper lantern quick-search does not function on Cloudflare plugin page

### ISSUE THREAD

**Issue by ron-bytes** [cloudflare/Cloudflare-CPanel#132]
cPanel version 11.60.0.37
Cloudflare plugin version 6.1.2

After opening the Cloudflare page in cPanel, the paper lantern quick search feature no longer works. If you enter anything in to the box, the quick-search drop-down does not functional at all.

Image 1 - How it works on every other cPanel page:

![image](https://cloud.githubusercontent.com/assets/2492319/23568817/f6a6e644-0021-11e7-8045-373cd1f8aef9.png)

Image 2 - How it works on the Cloudflare plugin page, note "add" is entered in to the box with no dropdown. The box is empty when the page is initially loaded.

![image](https://cloud.githubusercontent.com/assets/2492319/23568900/70748062-0022-11e7-941d-bc709acfe4eb.png)

Exact steps to replicate:
* Log in to cPanel for an account on the paper_lantern theme, "basic" style.
* Navigate to the Cloudflare plugin page
* Attempt to search for cPanel pages in the search drop-down

Issue:
No results are returned from the paper_lantern search box. Only occurs when on the Cloudflare page.

**Comment by jwineman** [comment]
@thellimist is your cPanel env on 60?  I only have 62.

**Comment by ronkh** [comment]
@jwineman No problem! I've actually been noticing this stuff for a while, but only recently saw how responsive you guys are on github. Its awesome you are staying on top of bug reports, and I'm happy to be able to help get some issues fixed. 👍
