### ISSUE TITLE
404 error, unable to log in

### ISSUE THREAD

**Issue by kardus** [cloudflare/Cloudflare-CPanel#134]
WHM/cPanel version 11.62.0.16 (clean install)
Plugin version 6.1.3

I'm not sure how to replicate this- on a clean install of 6.1.3 on a another new cPanel install, the installer seems to successfully install the plugin; however, when at the Cloudflare login screen in cPanel this error occurs when attemping to log in:

`Client error response [status code] 404 [reason phrase] Not Found [url] https://api.cloudflare.com/host-gw.html/host-gw.html`.

It seems the correct url is https://api.cloudflare.com/host-gw.html rather than https://api.cloudflare.com/host-gw.html/host-gw.html

Uninstalling/reinstalling doesn't seem to work either. I didn't seem to encouter this problem with 6.1.2 and have been using that version fine on another install.

**Comment by jwineman** [comment]
Hi,

Thanks for reporting this!  I'm able to reproduce and working on a fix.

Thanks,
John

**Comment by jwineman** [comment]
Tracking internally PI-1032

**Comment by jwineman** [comment]
Depends on: https://github.com/cloudflare/cloudflare-plugin-backend/pull/35

**Comment by jwineman** [comment]
Fixed https://github.com/cloudflare/Cloudflare-CPanel/pull/135

**Comment by jwineman** [comment]
Hi @kardus,

This should be fixed in https://github.com/cloudflare/Cloudflare-CPanel/releases/tag/v6.1.4.

Can you run
`/usr/local/cpanel/bin/cloudflare_update.sh force` 

And confirm its fixe?

Thanks,
John
