### ISSUE TITLE
"The name is already in use" issue

### ISSUE THREAD

**Issue by edgarasg** [cloudflare/Cloudflare-CPanel#140]
Just recently we started to face this error while trying to login to the CF account via CloudFlare plugin:

Taken from `/usr/local/cpanel/logs/error_log`:

```
PHP Fatal error:  Cannot use Psr\Log\LoggerInterface as LoggerInterface because the name is already in use in /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/cloudflare/cloudflare-plugin-backend/src/Integration/DefaultIntegration.php on line 5
```

This error appears when `http://*.*.*.*:2082/cpsess*******/frontend/paper_lantern/cloudflare/proxy.live.php` is executed. 

Plugin version: `6.1.5`
What we have already tried: reinstalling plugin, installing older versions, updating kernel, updating cPanel PHP to `5.6.30`, updating cPanel with `--force` switch.

Any thoughts?

**Comment by jwineman** [comment]
Can you uninstall and then check if `/usr/local/cpanel/3rdparty/php/**5.6**/lib/php/cloudflare/` and `/usr/local/cpanel/3rdparty/php/**5.4**/lib/php/cloudflare/` exists.  If they do can you remove them and try again?

**Comment by edgarasg** [comment]
Thanks, it seems that `cloudflare.install.sh` has an error on line 211:

```
CPANELSUPPORTEDPHPPATH=`ls -al $INSTALL_DIR/3rdparty/bin/php | awk '{print $11}'`
```

You should remove `awk` pipe as on our platform it was not updating your mentioned directories because the result of `PHPVERSION` variable was empty. Only after making these changes I was able to properly install the plugin and `/usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/` directory was created.

The final result should be:

```[root@xxx ~]# ls -al /usr/local/cpanel/3rdparty/bin/php | rev | cut -d '/' -f 3 | rev
56```

Your proposed `awk` pipe could get different results if the `ls -al` result has more columns.

**Comment by jwineman** [comment]
Thanks - this is good information! I'll look into testing this on my dev environment.  Can you give me the version of cPanel you're running and whether or not you're on CloudLinux too please?

**Comment by edgarasg** [comment]
Sure, we are using CloudLinux indeed:

`CLOUDLINUX 6.8`
`WHM 62.0 (build 16)`
