### ISSUE TITLE
Auto Minify settings not saving

### ISSUE THREAD

**Issue by rdetwiler** [cloudflare/Cloudflare-CPanel#142]
Hello, 
We're running plugin 6.1.5 and one of our customers noticed that none of the Auto Minify settings (js, css,html) save after checking them. Let me know what logs I can provide to help troubleshoot.

**Comment by thellimist** [comment]
Hi, 

Thank for notifying. We've a fix for it [here ](https://github.com/cloudflare/cloudflare-plugin-frontend/pull/116). The fix will be deployed in the next version. For now please use cloudflare.com

Thanks

**Comment by jwineman** [comment]
Lets keep this open until the fix is released.

**Comment by jwineman** [comment]
Fixed in [6.2.0](https://github.com/cloudflare/Cloudflare-CPanel/releases/tag/v6.2.0)
