### ISSUE TITLE
Zone information

### ISSUE THREAD

**Issue by kardus** [cloudflare/Cloudflare-CPanel#145]
It seems like in the current version, full zone information from cpanel isn't being transferred over to cloudflare for new domains added. MIssing cpanel aliases (ftp.domain.tld, cpanel.domain.tld, etc. in addition to TXT records for DKIM, spf, etc.)

The aliases alone sometimes seem to appear in the cloudflare cpanel plugin, but not on the cpanel site itself (only domain.tld and www.domain.tld appear on the cloudflare website)

**Comment by jwineman** [comment]
They appear gray clouded right?  Meaning they aren't being proxied through Cloudflare.  If you click the cloud it should change to orange and create the DNS record right?

Are you saying when you provision a zone using full zone provisioning that all the DNS records aren't being pushed?

**Comment by kardus** [comment]
> Are you saying when you provision a zone using full zone provisioning that all the DNS records aren't being pushed?

Correct. I've tried removing the domain from both the website and plugin and reprovisioning, but got the same results.

For recent domains that have been added, all the default + mail-specific records that are usually automatically generated don't appear consistent on both the cloudflare plugin within cpanel and when logging into cloudflare directly. For example:

http://i.imgur.com/EF2JLy9.png (cpanel plugin)
http://i.imgur.com/hzzu2bN.png (cloudflare website)

This happened for me with the latest version of the plugin.

In this case the cpanel A records appear on the plugin, but for some reason only the domain's main A-record and www cname record shows up on the cloudflare website. In both cases it's evident that the txt records don't show up at all, even though they are present in the zone info for that particular domain.

On another domain I added previously, the txt records actually showed up in the plugin interface but are still absent from the cloudflare website (in this case the cpanel alias A records actually showed up on cloudflare), so what ends up getting pushed/ignored doesn't exactly seem to be consistent in my case.

This behaviour is unlike the initial domains I had added to the plugin, which appear to be consistent/mirrored between cpanel-plugin-cloudflare website with all txt records + A records present

**Comment by kardus** [comment]
I had to migrate everything to a new cpanel server (unrelated to this problem) and it seems like with a fresh install of both cpanel and the plugin I'm not encountering these issues anymore. 

I did notice that in the plugin the ftp.* subdomain appears as a "CNAME" in the plugin but appears as an A record in both cpanel zone info and on the cloudflare site. The spf txt record is also absent from the plugin but appears to show up on the cloudflare website fine.

**Comment by jwineman** [comment]
I think this is a bug which will be fixed when we migrate to the new API.  In the V4 API if the zone is provisioned using full zone instead of CNAME the existing DNS records we create the zone with `jump_start = true` which:

> Automatically attempt to fetch existing DNS records

Right now full zone domains are being created through the host API which doesn't have the `jump_start` flag.  My team is actually migrating this call to the new API in a few months and once we switch the cPanel plugin it should resolve this issue.  

The work around is just to manually orange cloud the delta DNS records in the plugin.
