### ISSUE TITLE
Blank Cloudflare Page in cPanel

### ISSUE THREAD

**Issue by mesoterra** [cloudflare/Cloudflare-CPanel#152]
Hello all,

OS: CloudLinux release 7.3 (Yury Malyshev)
cPanel & WHM 64.0 (build 24)

After installing the cPanel plugin for Cloudflare the page it adds is blank.

When pulling up the Cloudflare option in cPanel the below is output in /usr/local/cpanel/logs/error_log

```
PHP Warning:  file_get_contents(config.js): failed to open stream: No such file or directory in /usr/local/cpanel/base/frontend/paper_lantern/cloudflare/index.live.php on line 6
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/cloudflare/cloudflare-plugin-backend/src/Integration/DefaultConfig.php on line 25
```

During installation the output is as follows.

```
bash <(curl -s https://raw.githubusercontent.com/cloudflare/CloudFlare-CPanel/master/cloudflare.install.sh) -k removed_for_security -n "removed_for_security"
Starting CloudFlare CPanel Installation...
Downloading and unpacking latest version v6.2.0...
install: cannot stat ‘Cloudflare-CPanel-6.2.0/config.json.sample’: No such file or directory
info [install_plugin] Installing to paper_lantern
info [install_plugin] Running sprite_generator
info [install_plugin] Queueing task to update API spec files
Plugin installed ok
Cleaning up
```

I have also been able to recreate the issue on a different server with the below specs.
CentOS Linux release 7.3.1611 (Core) 
cPanel & WHM 64.0 (build 33)

If you need any more information please let me know. Any help that can be provided would be awesome, even a ductape fix would work for now.

**Comment by thellimist** [comment]
The installation is a bug we're working on atm. For now you can use 

`https://raw.githubusercontent.com/cloudflare/Cloudflare-CPanel/v6.2.0/cloudflare.install.sh`

instead of

`https://raw.githubusercontent.com/cloudflare/CloudFlare-CPanel/master/cloudflare.install.sh`

in the curl function. 

Let me know how it goes. Thanks

**Comment by mesoterra** [comment]
Thank you. Confirmed fixed.

```
[root@host2 cloudflare]# bash <(curl -s https://raw.githubusercontent.com/cloudflare/Cloudflare-CPanel/v6.2.0/cloudflare.install.sh) -k removed_for_security -n "removed_for_security"
Starting CloudFlare CPanel Installation...
Downloading and unpacking latest version v6.2.0...
info [install_plugin] Installing to paper_lantern
info [install_plugin] Running sprite_generator
info [install_plugin] Queueing task to update API spec files
Plugin installed ok
Cleaning up
[root@host2 cloudflare]# 
```

**Comment by jwineman** [comment]
Lets keep this open until the fix is released.

**Comment by jwineman** [comment]
Tracking as PI-1209 internally.

**Comment by jwineman** [comment]
Fixed in https://github.com/cloudflare/Cloudflare-CPanel/releases/tag/v7.0.0
