### ISSUE TITLE
Full zone setup not properly sync'd

### ISSUE THREAD

**Issue by TaiSHiNet** [cloudflare/Cloudflare-CPanel#162]
Hi,

I went to full zone setup and I had to disable/enable my domain to get the record set on CF.
Is there any way to trigger a full sync?
May be related to #156 

Thanks!

**Comment by TaiSHiNet** [comment]
I just tested:
- Editing/adding a zone from the Zone Editor
- Editing/adding a zone from the Advanced Zone Editor

No changes on CloudFlare

**Comment by thellimist** [comment]
Did you add a record to your zone from Zone Editor/Advance Zone Editor? Addon Domains section is the way you can add new domains from CPanel.

**Comment by TaiSHiNet** [comment]
@thellimist no addon domain exist, it's the main one freshly moved to CF.
Steps as follow:
- Cloudflare plugin panel -> Full zone provisioning
- Set up DNS
- Setup completed (no records existed)

Only way to make records show up on CF was to orange cloud it, but I was missing the MX, TXT, everything else (and can't add them from the cPanel interface either using the Zone editor)

**Comment by thellimist** [comment]
Do `MX`, `TXT` and other records exists in Cloudflare.com DNS page? In the setup phase of cloudflare when you create a zone and move nameservers, there is a text letting you know that  Cloudflare might not have pulled all the records. Some records may be needed to be added manually unfortunately.

**Comment by TaiSHiNet** [comment]
I'll try a fresh new domain and let you know, I don't mind adding old records manually but it would become harder to maintain record creation/updates (DKIM/MX/etc that are done through cPanel)

**Comment by darktorana** [comment]
Regarding this issue,
We are finding our servers have this issue too, but not all of them.
Both servers are running identical hardware, in the same location, same IP range, same software and version of cPanel.

- Add domain.com to Server A
- Add Full Zone to cPanel
- All DNS Records including MX/TXT are added

Remove from CloudFlare and Server
- Add domain.com to Server B
- Add Full Zone to cPanel
- Only A/CNAME Records and the TXT for the DKIM, the MX record is completely absent.

The DNS on both servers is using the same Nameserver, and the records were identical on both cPanel accounts.

Is there anything I can get you to try and diagnose this issue?

**Comment by infomaniac50** [comment]
Might this have something to do with duplicate zone names. This cPanel plugin doesn't seem to handle duplicate names.

We have a dual stack IPv4 and IPv6 setup and the IPv6 records don't show up in the domains list. MX records don't show all of the rows that we have configured. We use Google for email and there should be 5 of them. We also use Mailgun and it should have two MX records. There are similar issues for other records types as well. Records bearing the same name seem to interfere with each other, regardless of whether they contain different values or even different records types.

Adding a new zone is likely broken for the same reason. When we setup our domain the cPanel plugin only synced about two thirds of the records it was supposed to. It synced about 50 records while the overall total is 84.

The Google Chrome developer console spits out a bunch of messages like this when you open the Cloudflare plugin page in cPanel. The phrases "unequal data" and "Using the earlier value." sounds like the data model or the UI code can't handle duplicate names.

```text
compiled.js:30 When merging two <REDACTED>, found unequal data in their "id" values. Using the earlier value. <REDACTED>
compiled.js:30 When merging two <REDACTED>, found unequal data in their "type" values. Using the earlier value. <REDACTED>
compiled.js:30 When merging two <REDACTED>, found unequal data in their "proxiable" values. Using the earlier value. <REDACTED>
compiled.js:30 When merging two <REDACTED>, found unequal data in their "modified_on" values. Using the earlier value. <REDACTED>
compiled.js:30 When merging two <REDACTED>, found unequal data in their "created_on" values. Using the earlier value. <REDACTED>
compiled.js:30 When merging two <REDACTED>, found unequal data in their "meta" values. Using the earlier value. <REDACTED>
compiled.js:30 When merging two <REDACTED>, found unequal data in their "type" values. Using the earlier value. <REDACTED>
compiled.js:30 When merging two <REDACTED>, found unequal data in their "content" values. Using the earlier value. <REDACTED>
```

**Comment by cuddylier** [comment]
Can confirm this is still an issue in latest version.

**Comment by joseaneto** [comment]
Same problem here.

**Comment by pleasance** [comment]
Been going on for years, working with a web host and we see this all the time when client use Cloudflare cPanel plugin and full zone method.
