### ISSUE TITLE
[Interface] Respect existing headers cache setting is missing

### ISSUE THREAD

**Issue by TaiSHiNet** [cloudflare/Cloudflare-CPanel#163]
When I try to set "Respect existing headers" through the cPanel plugin, it's missing. 
I had to do straight from the CloudFlare web

**Comment by thellimist** [comment]
The plugin does not have all the features from the dashboard. It only has features which are most common or most important for CPanel users.

**Comment by TaiSHiNet** [comment]
Excellent then, I'll go ahead and close this

**Comment by thellimist** [comment]
FYI https://github.com/cloudflare/cloudflare-plugin-frontend/blob/master/CONTRIBUTING.md
