### ISSUE TITLE
[Interface] Row gets duplicated (visually) when enabling proxy

### ISSUE THREAD

**Issue by TaiSHiNet** [cloudflare/Cloudflare-CPanel#164]
This is quite specific:
If you enable proxy on a record that doesn't exists (#162), the row will get duplicated. Further action (even refreshing/disabling/reenabling/etc) wont cause the same behavior.
Screenshot attached
![photo_2017-10-09_14-17-08](https://user-images.githubusercontent.com/6354880/31350163-8c1acaba-acfc-11e7-9319-6fb57710a01e.jpg) 
(pardon the crappy image edit)

**Comment by thellimist** [comment]
This is a known issue. It is most probably caused from the [frontend](https://github.com/cloudflare/cloudflare-plugin-frontend)

https://github.com/cloudflare/cloudflare-plugin-frontend/blob/8d58b4fa2523d1e6b72671e6245143c3351df7ae/src/containers/DNSRecordEditor/DNSRecordEditor.js#L22-L36

We have this tracked but haven't had time to fix it. You're welcome to open a PR :)
