### ISSUE TITLE
No or invalid host_key.

### ISSUE THREAD

**Issue by slrslr** [cloudflare/Cloudflare-CPanel#165]
Hello,

on my WHM/cPanel (v68.0.19) server when i login cPanel and click Cloudflare icon, i submit login form and it says: "No or invalid host_key." on that cPanel/cloudflare page i see: Version: 6.1.5
Is there any file where i can update the key? I am afraid to do uninstall as i do not want to remove cpanel users cloudflare connection (when they logged in using their login data and enabled cloudflare via cpanel).

At https://partners.cloudflare.com/dashboard i login and i have there API key and name.

$ /usr/local/cpanel/bin/cloudflare_update.sh
cat: /root/.cpanel/datastore/cf_api: No such file or directory
ERROR - Missing HOST_KEY

Thank you in advance for suggestion.

**Comment by thellimist** [comment]
I recommend you to uninstall and reinstall the plugin. Info about both can be found here https://github.com/cloudflare/Cloudflare-CPanel

**Comment by slrslr** [comment]
Thanks, but You have not cleared my question/doubt regarding uninstallation:

> I am afraid to do uninstall as i do not want to remove cpanel users cloudflare connection (when they logged in using their login data and enabled cloudflare via cpanel).

**Comment by thellimist** [comment]
If you use `cloudflare_update.sh` the problem you mentioned won't happen however the latest code is not released yet. I'll notify you when I do a release.

**Comment by slrslr** [comment]
Thank You, update does not work:

> $ /usr/local/cpanel/bin/cloudflare_update.sh
> cat: /root/.cpanel/datastore/cf_api: No such file or directory
> ERROR - Missing HOST_KEY

i think it is because it happened to me once that my root directory contents got wiped. Do you recommend me to somehow run installation again and it will not overwrite my curent settings and cpanel users will not loose their settings/cloudflare connection?

I assume this would be the installation command:

> bash <(curl -s https://raw.githubusercontent.com/cloudflare/CloudFlare-CPanel/master/cloudflare.install.sh) -k [YOUR_HOST_API_KEY] -n '[YOUR_COMPANY_NAME]'

Thank you in advance for the feedback.

**Comment by thellimist** [comment]
I didn't realize the root directory was wiped. You can do a quick fix

```
echo "yourhostkey" > /root/.cpanel/datastore/cf_api
chmod 600 /root/.cpanel/datastore/cf_api
```

**Comment by slrslr** [comment]
thank you very much, it solved the issue.
