### ISSUE TITLE
Error Uncaught exception - cpanel 

### ISSUE THREAD

**Issue by dzamanakos** [cloudflare/CloudFlare-CPanel#169]
Hi, i'm getting an infinite loading when clicking on cpanel's cloudflare icon.

The error i get in /usr/local/cpanel/logs/error_log is : 

Use of uninitialized value in concatenation (.) or string at /usr/local/cpanel/Cpanel/AdminBin/Server.pm line 339, <$socket> line 1.
PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\ServerException' with message 'Server error response [url] https://api.cloudflare.com/client/v4/zones/?name=chaton.gr [status code] 500 [reason phrase] Internal Server Error' in /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:89
Stack trace:
#0 /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/Subscriber/HttpError.php(33): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Message\Response))
#1 /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/Event/Emitter.php(108): GuzzleHttp\Subscriber\HttpError->onComplete(Object(GuzzleHttp\Event\CompleteEvent), 'complete')
#2 /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/RequestFsm.php(91): GuzzleHttp\Event\Emitter->emit('complete', Object(GuzzleHttp\Event\CompleteEvent))
#3 /usr/local/cpanel/3rdparty/php/56/lib/php/clou in /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 89

i've tried to reinstall without any luck.

best regards,

**Comment by marbman21** [comment]
Did you ever find a solution to this problem?

**Comment by dzamanakos** [comment]
Hi, it was a problem with cloudflare network in my country (couldnt even connect to their website). It was ok, after the connection problem restored.
