### ISSUE TITLE
Not loading.

### ISSUE THREAD

**Issue by marbman21** [cloudflare/CloudFlare-CPanel#173]
The cloudflare plugin will not load on one of our servers. It has been working fine for years and even a reinstall would not work. The page loads, but the loading circle just continues to spin without ever loading the options.

Here is the cpanel error below. Substituted the real domain for domain.com:

`PHP Warning:  file_get_contents(config.js): failed to open stream: No such file or directory in /usr/local/cpanel/base/frontend/paper_lantern/cloudflare/index.live.php on line 6
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/cloudflare/cloudflare-plugin-backend/src/Integration/DefaultConfig.php on line 25
Use of uninitialized value in concatenation (.) or string at /usr/local/cpanel/Cpanel/AdminBin/Server.pm line 339, <$socket> line 1.
PHP Warning:  file_get_contents(config.js): failed to open stream: No such file or directory in /usr/local/cpanel/base/frontend/paper_lantern/cloudflare/proxy.live.php on line 15
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/cloudflare/cloudflare-plugin-backend/src/Integration/DefaultConfig.php on line 25
PHP Warning:  file_get_contents(config.js): failed to open stream: No such file or directory in /usr/local/cpanel/base/frontend/paper_lantern/cloudflare/proxy.live.php on line 15
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/cloudflare/cloudflare-plugin-backend/src/Integration/DefaultConfig.php on line 25
PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error response [url] https://api.cloudflare.com/client/v4/zones/?name=domain.com [status code] 403 [reason phrase] Forbidden' in /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:89
Stack trace:
#0 /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/Subscriber/HttpError.php(33): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Message\Response))
#1 /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/Event/Emitter.php(108): GuzzleHttp\Subscriber\HttpError->onComplete(Object(GuzzleHttp\Event\CompleteEvent), 'complete')
#2 /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/RequestFsm.php(91): GuzzleHttp\Event\Emitter->emit('complete', Object(GuzzleHttp\Event\CompleteEvent))
#3 /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vend in /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 89
PHP Warning:  file_get_contents(config.js): failed to open stream: No such file or directory in /usr/local/cpanel/base/frontend/paper_lantern/cloudflare/index.live.php on line 6
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/cloudflare/cloudflare-plugin-backend/src/Integration/DefaultConfig.php on line 25
Use of uninitialized value in concatenation (.) or string at /usr/local/cpanel/Cpanel/AdminBin/Server.pm line 339, <$socket> line 1.
PHP Warning:  file_get_contents(config.js): failed to open stream: No such file or directory in /usr/local/cpanel/base/frontend/paper_lantern/cloudflare/proxy.live.php on line 15
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/cloudflare/cloudflare-plugin-backend/src/Integration/DefaultConfig.php on line 25
PHP Warning:  file_get_contents(config.js): failed to open stream: No such file or directory in /usr/local/cpanel/base/frontend/paper_lantern/cloudflare/proxy.live.php on line 15
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/cloudflare/cloudflare-plugin-backend/src/Integration/DefaultConfig.php on line 25
PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error response [url] https://api.cloudflare.com/client/v4/zones/?name=domain.com [status code] 403 [reason phrase] Forbidden' in /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:89
Stack trace:
#0 /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/Subscriber/HttpError.php(33): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Message\Response))
#1 /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/Event/Emitter.php(108): GuzzleHttp\Subscriber\HttpError->onComplete(Object(GuzzleHttp\Event\CompleteEvent), 'complete')
#2 /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/RequestFsm.php(91): GuzzleHttp\Event\Emitter->emit('complete', Object(GuzzleHttp\Event\CompleteEvent))
#3 /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vend in /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 89
PHP Warning:  file_get_contents(config.js): failed to open stream: No such file or directory in /usr/local/cpanel/base/frontend/paper_lantern/cloudflare/index.live.php on line 6
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/cloudflare/cloudflare-plugin-backend/src/Integration/DefaultConfig.php on line 25
Use of uninitialized value in concatenation (.) or string at /usr/local/cpanel/Cpanel/AdminBin/Server.pm line 339, <$socket> line 1.
PHP Warning:  file_get_contents(config.js): failed to open stream: No such file or directory in /usr/local/cpanel/base/frontend/paper_lantern/cloudflare/proxy.live.php on line 15
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/cloudflare/cloudflare-plugin-backend/src/Integration/DefaultConfig.php on line 25
PHP Warning:  file_get_contents(config.js): failed to open stream: No such file or directory in /usr/local/cpanel/base/frontend/paper_lantern/cloudflare/proxy.live.php on line 15
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/cloudflare/cloudflare-plugin-backend/src/Integration/DefaultConfig.php on line 25
PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error response [url] https://api.cloudflare.com/client/v4/zones/?name=domain.com [status code] 403 [reason phrase] Forbidden' in /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:89
Stack trace:
#0 /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/Subscriber/HttpError.php(33): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Message\Response))
#1 /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/Event/Emitter.php(108): GuzzleHttp\Subscriber\HttpError->onComplete(Object(GuzzleHttp\Event\CompleteEvent), 'complete')
#2 /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/RequestFsm.php(91): GuzzleHttp\Event\Emitter->emit('complete', Object(GuzzleHttp\Event\CompleteEvent))
#3 /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vend in /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 89
[2018-08-29 01:57:28 +0200] info [gather-update-logs] Cannot send file /usr/local/cpanel/logs/update_analysis/2018-08-28T23:57:24Z.tar.gz to updatelogdrop.cpanel.net: 500 Internal Server Error
[2018-08-29 01:57:28 +0200] info [gather-update-logs] Failed to send data to cPanel
PHP Warning:  file_get_contents(config.js): failed to open stream: No such file or directory in /usr/local/cpanel/base/frontend/paper_lantern/cloudflare/index.live.php on line 6
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/cloudflare/cloudflare-plugin-backend/src/Integration/DefaultConfig.php on line 25
Use of uninitialized value in concatenation (.) or string at /usr/local/cpanel/Cpanel/AdminBin/Server.pm line 339, <$socket> line 1.
PHP Warning:  file_get_contents(config.js): failed to open stream: No such file or directory in /usr/local/cpanel/base/frontend/paper_lantern/cloudflare/proxy.live.php on line 15
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/cloudflare/cloudflare-plugin-backend/src/Integration/DefaultConfig.php on line 25
PHP Warning:  file_get_contents(config.js): failed to open stream: No such file or directory in /usr/local/cpanel/base/frontend/paper_lantern/cloudflare/proxy.live.php on line 15
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/cloudflare/cloudflare-plugin-backend/src/Integration/DefaultConfig.php on line 25
PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error response [url] https://api.cloudflare.com/client/v4/zones/?name=domain.com [status code] 403 [reason phrase] Forbidden' in /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:89
Stack trace:
#0 /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/Subscriber/HttpError.php(33): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Message\Response))
#1 /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/Event/Emitter.php(108): GuzzleHttp\Subscriber\HttpError->onComplete(Object(GuzzleHttp\Event\CompleteEvent), 'complete')
#2 /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/RequestFsm.php(91): GuzzleHttp\Event\Emitter->emit('complete', Object(GuzzleHttp\Event\CompleteEvent))
#3 /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vend in /usr/local/cpanel/3rdparty/php/56/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 89`

**Comment by spignataro** [comment]
Has anyone solved this as of yet? We are having the same issue - might this be a firewall related issue?

**Comment by marbman21** [comment]
No fix here. Still dealing with the same damn issue and it is apparent you can't get support around here.

**Comment by spignataro** [comment]
I am working with the same issue and hope to resolve it - I will post back my findings.

**Comment by spignataro** [comment]
So the issue was a bit complicated to figure out. So I am hoping that I can make it simplified for you to fix.

Gather a few things:
- Your login email address for cloudflare.com (not your partner login - although they might be the same)
- Login to your partner account and get your API key

Open a terminal and do the following:
nano /home/ACCOUNT_NAME/.cpanel/datastore/cloudflare_data.yaml

Now open POST MAN (https://www.getpostman.com/) - just so that you can format the json response

Put in a POST URL like the following

https://api.cloudflare.com/host-gw.html?host_key=PARTNER_API_KEY&act=user_lookup&cloudflare_email=YOUR_CLOUDFLARE_ACCOUNT_EMAIL

You should get a response.

Now match the keys up with that in your cloudflare_data.yml file and it should correct the issues you are having. It did for me.
