### ISSUE TITLE
Child failed to make LIVEAPI connection to cPanel

### ISSUE THREAD

**Issue by Veeau** [cloudflare/CloudFlare-CPanel#174]
Since Cpanel 76.0.6 update the plugin returns this error.

"Implemented case CPANEL-22332: Update cPanel internal PHP to upstream version 7.2.7"

https://forums.cpanel.net/threads/after-76-x-update-child-failed-to-make-liveapi-connection-to-cpanel.641153/#post-2612525

**Comment by Sn0wCrack** [comment]
You should be able to run the installation script again:

```
bash <(curl -s https://raw.githubusercontent.com/cloudflare/CloudFlare-CPanel/master/cloudflare.install.sh) -k [YOUR_HOST_API_KEY] -n '[YOUR_COMPANY_NAME]'
```

The main issue is that cPanel 76.0.6 uses a different version of the ionCube Encoder, so the plugin basically has to be recompiled due to this change.

**Comment by Veeau** [comment]
Great thanks! this seems to have fixed it. I did not realize re running it would recompile it.

**Comment by daniellee-dp** [comment]
Hello,

We usually fix this issue by re-installing every time there is a cPanel update. Yet, this does not do the trick this time. We have attempted to reinstall multiple times, even completely uninstall/install again, but this error keeps coming up. The cPanel error log indicates:

PHP Warning:  require_once(cloudflare/vendor/autoload.php): failed to open stream: No such file or directory in /usr/local/cpanel/base/frontend/paper_lantern/cloudflare/index.live.php on line 2
PHP Fatal error:  require_once(): Failed opening required 'cloudflare/vendor/autoload.php' (include_path='/usr/local/cpanel/3rdparty/php/56/lib/php:.') in /usr/local/cpanel/base/frontend/paper_lantern/cloudflare/index.live.php on line 2
[2018-12-03 15:33:02 +0000] die [Internal Death while parsing [live php] 307] Child failed to make LIVEAPI connection to cPanel from: ./frontend/paper_lantern/cloudflare/index.live.php. at cpanel.pl line 4271.
 at cpanel.pl line 4271.
        cpanel::cpanel::setup_external_engine() called at cpanel.pl line 801
        cpanel::cpanel::script("cpanel::cpanel", "./frontend/paper_lantern/cloudflare/index.live.php") called at cpanel.pl line 267

We are using the latest General Availability cPanel version 76.0.10 on this server, even forced an upcp just in case. We would appreciate some help.

Best Regards,

**Comment by andrekutianski** [comment]
Works here!

**Comment by Sn0wCrack** [comment]
@daniellee-dp Issue there looks like your PHP path for whatever reason.

CloudFlare's plugin installer will install the vendor folder from the git repo in the following directory: 
/usr/local/cpanel/3rdparty/php/$PHPVERSION/lib/php/cloudflare/vendor

In cPanel 76.0.6 they moved over to PHP 7.2 as the internal PHP version that cPanel uses, but it appears your include path for the internal PHP is set to php56, thus the conflict here, you may have manually edited the include path in the past and might need to update it.  

A /scripts/upcp --force might do it for you.
