### ISSUE TITLE
/scripts/postupcp does not force plugin reinstall

### ISSUE THREAD

**Issue by Pugasus** [cloudflare/CloudFlare-CPanel#175]
The entry in /scripts/postupcp calls cloudflare_update.sh with the argument "force".

`sh /usr/local/cpanel/bin/cloudflare_update.sh force`

But the update script expects the argument -f to run the upgrade with a forced reinstall.
`/usr/local/cpanel/bin/cloudflare_update.sh -f`

Calling the script with 'force' results in nothing being executed.

postupcp line should be changed to use -f

**Comment by edgarasg** [comment]
https://github.com/cloudflare/Cloudflare-CPanel/pull/177 fixes it :)

**Comment by mauamolat** [comment]
How do we re-install or update using these commands in whm/cpanel? Thanks
