### ISSUE TITLE
Infinite loading Version: 7.0.1

### ISSUE THREAD

**Issue by masfernandez** [cloudflare/CloudFlare-CPanel#176]
Hello,

I have just realized that CF plugin never loads Cloudfare interface on cPanel server.

I have removed and install again the plugin and have exact same problem.

Please see browser console log:

![cf_console](https://user-images.githubusercontent.com/25205930/50608135-ec78cb00-0ecb-11e9-88b1-1d3d4b606b07.png)

and cPanel error logs: `tail -f /usr/local/cpanel/logs/error_log`

`PHP Warning:  file_get_contents(config.js): failed to open stream: No such file or directory in /usr/local/cpanel/base/frontend/paper_lantern/cloudflare/index.live.php on line 6
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /usr/local/cpanel/3rdparty/php/72/lib/php/cloudflare/vendor/cloudflare/cloudflare-plugin-backend/src/Integration/DefaultConfig.php on line 25
Use of uninitialized value in concatenation (.) or string at /usr/local/cpanel/Cpanel/AdminBin/Server.pm line 339, <GEN1727> line 1.
PHP Warning:  file_get_contents(config.js): failed to open stream: No such file or directory in /usr/local/cpanel/base/frontend/paper_lantern/cloudflare/proxy.live.php on line 15
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /usr/local/cpanel/3rdparty/php/72/lib/php/cloudflare/vendor/cloudflare/cloudflare-plugin-backend/src/Integration/DefaultConfig.php on line 25
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error response [url] https://api.cloudflare.com/client/v4/zones/?name=masfernandez.com [status code] 403 [reason phrase] Forbidden in /usr/local/cpanel/3rdparty/php/72/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:89
Stack trace:
#0 /usr/local/cpanel/3rdparty/php/72/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/Subscriber/HttpError.php(32): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Message\Response))
#1 /usr/local/cpanel/3rdparty/php/72/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/Event/Emitter.php(108): GuzzleHttp\Subscriber\HttpError->onComplete(Object(GuzzleHttp\Event\CompleteEvent), 'complete')
#2 /usr/local/cpanel/3rdparty/php/72/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/RequestFsm.php(91): GuzzleHttp\Event\Emitter->emit('complete', Object(GuzzleHttp\Event\CompleteEvent))
#3 /usr/local/cpanel/3rdparty/php/72/lib/php/cloudflare/vendor/guzzlehttp/guzzle in /usr/local/cpanel/3rdparty/php/72/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 89
PHP Warning:  file_get_contents(config.js): failed to open stream: No such file or directory in /usr/local/cpanel/base/frontend/paper_lantern/cloudflare/proxy.live.php on line 15
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /usr/local/cpanel/3rdparty/php/72/lib/php/cloudflare/vendor/cloudflare/cloudflare-plugin-backend/src/Integration/DefaultConfig.php on line 25`

Same error like [this](https://github.com/cloudflare/Cloudflare-CPanel/issues/119) 

Server: CLOUDLINUX 7.6, cPanel v76.0.14 

Thanks,
Miguel Ángel

**Comment by infomaniac50** [comment]
This might be related to #173 and #160.

Do you have CageFS enabled for this user? It might be worth checking that the skeleton directory is update to date. You can do this manually by running ``cagefsctl --force-update`` as root. You can also do this from the CageFS plugin page in WHM.

I doubt this is the case though. The PHP script is looking for config.js on the server side. It's not like the web server is doing an HTTP request. For root this file should be located in ``/usr/local/cpanel/base/frontend/paper_lantern/cloudflare``.

According to index.live.php and proxy.live.php, config.js is missing. It might be worth going through the installation guide again. [Installation Guide: cPanel Plugin](https://www.cloudflare.com/static/media/pdf/cloudflare-cpanel-installation-activation-guide.pdf) This link is referenced from https://partners.cloudflare.com/downloads under "Control Panel Plugins > cPanel".

For reference this is what my config.js contains:
```javascript
{
  "debug": false,
  "featureManagerIsFullZoneProvisioningEnabled": true,
  "locale": "en"
}
```

**Comment by masfernandez** [comment]
Thanks for your response @infomaniac50

The problem was related to /home/<username>/.cpanel/datastore/cloudflare_data.yaml file and I resolved it with:

`rm -rf /home/<username>/.cpanel/datastore/cloudflare_data.yaml`

After delete the file, user have to login again and everything will work again

**Comment by ronkh** [comment]
I am reopening this issue because my team recently had this same problem. The issue appears to not be specific to any environment settings. We had a user failing with the same errors as noted here. There were other PHP warnings but they seem to be side-effects of this failure. Force reinstall doesn't help, the error is isolated to the user's current `cloudflare_data.yaml` settings.

```
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error response [url] https://api.cloudflare.com/client/v4/zones/?name=DOMAIN_REDACTED [status code] 403 [reason phrase] Forbidden in /usr/local/cpanel/3rdparty/php/72/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:89
Stack trace:
#0 /usr/local/cpanel/3rdparty/php/72/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/Subscriber/HttpError.php(32): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Message\Response))
#1 /usr/local/cpanel/3rdparty/php/72/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/Event/Emitter.php(108): GuzzleHttp\Subscriber\HttpError->onComplete(Object(GuzzleHttp\Event\CompleteEvent), 'complete')
#2 /usr/local/cpanel/3rdparty/php/72/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/RequestFsm.php(91): GuzzleHttp\Event\Emitter->emit('complete', Object(GuzzleHttp\Event\CompleteEvent))
#3 /usr/local/cpanel/3rdparty/php/72/lib/php/cloudflare/vendor/guzzlehttp/guzzle/s in /usr/local/cpanel/3rdparty/php/72/lib/php/cloudflare/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 89
```


We had to rename `cloudflare_data.yaml` to clear the user data and force the customer to log in again. This appears to fix the issue.

`root@vps [/home/sdgtesti/.cpanel/datastore]# mv cloudflare_data.yaml cloudflare_data.yaml_bak`


All data in `cloudflare_data.yaml` looked normal, except for this line:

```
host_user_unique_id: null
```

The values for `client_api_key`, `cloudflare_email`, and `host_user_key` were all normal. Only `host_user_unique_id` was set to `null`, which seemed odd. However I checked other active accounts and their `host_user_unique_id` was null, so this appears to be normal?

Please let me know any steps I can take to assist with debugging this further. It would be nice to see a proper fix for this instead of having to rename the user's Cloudflare datastore files to force a relogin. This does resolve the issue but is inconvenient for the customer.
