### ISSUE TITLE
Problem with config.js file (Translation Portuguese Brazil)

### ISSUE THREAD

**Issue by suportgc** [cloudflare/CloudFlare-CPanel#180]
Hello people good night

I did the translation of the whole en.js file to ptbr.js
However, when I insert this into the config.js file nothing happens.
I saw that it worked fine if I change the ptbr.js file to en.js (removing the original en.js)
However I keep ptbr.js and adjust the file config.js. does not work.

Can you help me ?

My config.js file looks like this: 
{
  "debug": false,
  "featureManagerIsFullZoneProvisioningEnabled": false,
  "locale": "ptbr"
}

Here is my translated file.
I think it can help Brazilians.
If you can insert it into your project, it will be cool: #181

**Comment by splaquet** [comment]
see if changing the extension to .json works.

i was reading through the steps again, and went to edit:
` /usr/local/cpanel/base/frontend/paper_lantern/Cloudflare/config.js`

for 1, that file didn't exist.
2, the path is incorrect.  it should be lowercase:
`/usr/local/cpanel/base/frontend/paper_lantern/cloudflare`
3, the file that existed was: **config.json.sample** ...and there was no **config.js**

i reinstalled the cPanel plugin today, so i found that all kinda odd.  my guess is that they've updated their software w/o updating their manuals.
