### ISSUE TITLE
CNAME setup: advanced DNS zone editor deprecated

### ISSUE THREAD

**Issue by BenjaminEHowe** [cloudflare/CloudFlare-CPanel#182]
[The advanced DNS zone editor is deprecated](https://confluence2.cpanel.net/plugins/servlet/mobile?contentId=1794381#content/view/1794381) (it actually doesn't even exist on my RamNode plan!), so I'm struggling to set up my domain using CNAME. Please could you update the plugin to use the "zone editor", which is the replacement functionality?

**Comment by yuliu** [comment]
Hi @BenjaminEHowe !

Are you still using cPanel from Ramnode for Cloudflare integration? Did you have issues with them? Currently I can't get edited zone records populated from cPanel to Cloudflare's end.

**Comment by BenjaminEHowe** [comment]
No, I gave up. I'm guessing this won't get fixed because CNAME functionality is usually reserved for the enterprise plan...
