### ISSUE TITLE
Cloudflare plugin (version 7.0.1) uses cPanel API 1

### ISSUE THREAD

**Issue by support-s** [cloudflare/CloudFlare-CPanel#185]
We noticed an alert from cPanel about the fact that Cloudflare plugin uses cPanel API 1. Also, there are a lot of errors in /usr/local/cpanel/logs/error_log [1]. 

Do you plan to switch the plugin from cPanel API 1 to cPanel API 2 and if so, when?

[1]
[2020-03-16 13:10:48 +0100] info [cpanel] Filemanager::get_file_content => The file <E2><80><9C>/home/XXXXX/.cpanel/datastore/cloudflare_data.yaml<E2>
<80><9D> does not exist for the account.
[Cloudflare] ERROR: [CPANEL UAPI] Array
(
    [type] => response
    [body] => Array
        (
            [cpanelresult] => Array
                (
                    [module] => Fileman
                    [result] => Array
                        (
                            [warnings] =>
                            [status] => 0
                            [data] =>
                            [errors] => Array
                                (
                                    [0] => The file <E2><80><9C>/home/XXXXX/.cpanel/datastore/cloudflare_data.yaml<E2><80><9D> does not exist for the account.
                                )

                            [messages] =>
                            [metadata] => Array
                                (
                                )

                        )

                    [func] => get_file_content
                    [apiversion] => 3
                )

        )

)

[Deprecated cPanel API 1 usage detected on your server.txt](https://github.com/cloudflare/Cloudflare-CPanel/files/4338520/Deprecated.cPanel.API.1.usage.detected.on.your.server.txt)

**Comment by Firefall-scott** [comment]
I'm attaching a rich-text version of the warning. I'd PDF it but it has full e-mail addresses. I figure this is going to effect a lot of servers. I don't use the Cloudflare interface in cPanel a huge amount, but I do use the CSF/LDF Cloudflare functionality which requires cPanel users to be logged into Cloudflare via the plugin.

[Deprecated cPanel API 1 usage detected on your server. Action required..rtfd.zip](https://github.com/cloudflare/Cloudflare-CPanel/files/4344680/Deprecated.cPanel.API.1.usage.detected.on.your.server.Action.required.rtfd.zip)

**Comment by djprmf** [comment]
The Cloudflare plugin is outdated from a long time ago. It have received less and less updates in the past few months (or even years?).
This will probably be - once again - ignored or delay. Is sad to see that Cloudflare isn't even treating the hosting partners with a decent option this days. In the "past", when they really do care, there was a active help and incentive to be a partner from Cloudflare - and in part the companyes help them be what they are now. So this is a little sad to see..

Rant over, maybe this could help everyone in the Cloudflare Team to migrate: https://documentation.cpanel.net/display/DD/Guide+to+Replacing+cPanel+API+1+Functions+with+UAPI+Equivalents

**Comment by kporembinski** [comment]
I have send support request to update this plugin.

**Comment by djprmf** [comment]
This was the support answer from my end:

"Thanks for contacting Cloudflare support. 
Cloudflare will no longer be updating our cPanel/WHM plugin and it is soon going to be marked end of life. We have not announced this yet, and we are waiting on an announcement from our partners team - but you should expect that this will not be updated."

So, the cPanel plugin is dead….
