### ISSUE TITLE
Issue with DKIM records when using Full Zone Setup

### ISSUE THREAD

**Issue by sstoilovABLE** [cloudflare/CloudFlare-CPanel#186]
Before turning on Cloudflare, my domain has a custom TXT DKIM record, entered through the cPanel Zone Editor and functioning correctly. The DKIM record is a 2048-bit RSA key generated through Google (as we use Google G Suite as the email provider).

The value of the record is:
> v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAibT8LGvNQ+6+tSRterbmI8bOfEDN0jX3qbZajCcOpZnieXcGwlxshEl9TV4KZlnseAnowIDYeSeRkNfp9DDW0deXnOi0j9vqNJwfnlfvKmUqup86DC3g+/3lMZ/hpqnjj6FsYp9xcbfCm832MOFcATxCg3aevZS5/it+CpSuRWSuCNZKwuaIwONQOxBRdkbq+JXS87ttTKJDB4a8Uu/uGbrPdx3B510ZPyJhkJKgX7jgxIPbnqywFB1wimdNPI0jLX4+8+L8vJaqXYLtao3Y4gHRn5GM/+/MkCi4jXhkgyi9tw5cST+t9ptkBSl0iY0RZBhB0oQlrNted+gVXhhGmwIDAQAB

When I use the Cloudflare cPanel plugin to do a Full Zone Setup, all the DNS records are uploaded to Cloudflare. However, the TXT DKIM record becomes the following:

> v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAibT8LGvNQ+6+tSRterbmI8bOfEDN0jX3qbZajCcOpZnieXcGwlxshEl9TV4KZlnseAnowIDYeSeRkNfp9DDW0deXnOi0j9vqNJwfnlfvKmUqup86DC3g+/3lMZ/hpqnjj6FsYp9xcbfCm832MOFcATxCg3aevZS5/it+CpSuRWSuCNZKwuaIwONQOxBRdkbq+" "JXS87ttTKJDB4a8Uu/uGbrPdx3B510ZPyJhkJKgX7jgxIPbnqywFB1wimdNPI0jLX4+8+L8vJaqXYLtao3Y4gHRn5GM/+/MkCi4jXhkgyi9tw5cST+t9ptkBSl0iY0RZBhB0oQlrNted+gVXhhGmwIDAQAB

Do you see it? There is a `" "` inserted in the middle of the TXT record value. Note, both TXT records here are one-line text strings. 

This makes the RSA key invalid, and so it breaks our DKIM authentication, which is how I found this.

Upon further investigation, it looks like the `" "` break comes after the first 255 characters of the record string. I am unaware if this comes from the way cPanel stores the record value internally, or in the way the Cloudflare plugin handles it.

If I go to the Cloudflare dashboard and fix the record there manually - all works perfectly!

Our shared hosting provider is SuperHosting.BG, using cPanel version 86.0 (build 21). The Cloudflare plugin is v7.0.1.

**Comment by djprmf** [comment]
This plugin is no longer supported by Cloudflare:
https://github.com/cloudflare/Cloudflare-CPanel/issues/185
