### ISSUE TITLE
No or invalid host_key

### ISSUE THREAD

**Issue by imorandinwnp** [cloudflare/CloudFlare-CPanel#187]
Hi,

I have the same problem stated here: https://github.com/cloudflare/Cloudflare-CPanel/issues/165
The file "/root/.cpanel/datastore/cf_api" disappears randomly and have to reinstall the plugin (or restore the file).
I think this is because the folder "/root/.cpanel/datastore/" is some sort of cPanel's cache so maybe an internal cron is removing it: https://forums.cpanel.net/threads/root-cpanel-datastore-folder-question.624307/

I would recommend to place this file into another folder if possible.

**Comment by mmuyskens** [comment]
Anyone have a working solution to this? I know this is old, but getting tired of having to reinstall all the time.

**Comment by imorandinwnp** [comment]
@mmuyskens : seems that CF team is not into this plugin... to solve the problem I simply created a cronjob to reinstall CF plugin in a weekly basis.

**Comment by mmuyskens** [comment]
@imorandinwnp have you tried using chattr to just make the file immutable? trying to come up with a more viable option besides the constant reinstalls but might consider the cron option.

**Comment by imorandinwnp** [comment]
@mmuyskens : I created a cron that reinstalls the plugin every day. This has the benefit that in the case they (ever) update the plugin, it will update itself.
