### ISSUE TITLE
ERROR - Unpack failed, directory not found: 'Cloudflare-CPanel-7.0.1'

### ISSUE THREAD

**Issue by imorandinwnp** [cloudflare/CloudFlare-CPanel#189]
Hi,

Trying to install plugin shows this error:

```
# bash <(curl -s https://raw.githubusercontent.com/cloudflare/CloudFlare-CPanel/master/cloudflare.install.sh) -k XXXX -n 'DOMAIN.COM'
Starting CloudFlare CPanel Installation...
Downloading and unpacking latest version v7.0.1...

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
ERROR - Unpack failed, directory not found: 'Cloudflare-CPanel-7.0.1'
```

I think it's because it can't download the plugin file:

https://github.com/cloudflare/CloudFlare-CPanel/archive/v7.0.1.tar.gz

Trying to download this file directly shows this error:

`the given path has multiple possibilities: #<Git::Ref:0x00007f50447f6160>, #<Git::Ref:0x00007f50447fb8e0>`

Ignacio

**Comment by imorandinwnp** [comment]
Downloading the file from this URL seems to work fine: https://codeload.github.com/cloudflare/Cloudflare-CPanel/tar.gz/refs/tags/v7.0.1

**Comment by ramphy** [comment]
Use this link from a change made from @liamcottam

bash <(curl -s https://raw.githubusercontent.com/liamcottam/Cloudflare-CPanel/master/cloudflare.install.sh) -k KEY_KEY -n 'COMPANY_NAME'
