### ISSUE TITLE
Add more information to cPanel page

### ISSUE THREAD

**Issue by SimonEast** [cloudflare/CloudFlare-CPanel#20]
Would it be worth adding more details to the cPanel screen to explain the difference between CloudFlare-controlled DNS and host-controlled DNS?  Or perhaps at least link to a CloudFlare knowledge base page.  Things like...

### Using CloudFlare DNS
* Provides faster DNS resolution with servers distributed around the world
* Your IP address is more veiled from the internet and less vulnerable to DDOS attacks
* Allows the root/naked domain to be routed through CloudFlare, not just the "www" domain and subdomains.
* Subdomains created via cPanel will *not* work automatically.  They will need to be manually added to CloudFlare.  (Unless the plugin can be made to do this?)
* To activate this, you must *disable* CloudFlare within cPanel, *enable* it via cloudflare.com and then follow the instructions in changing your nameservers
* RailGun will only be available for business/enterprise accounts.

### Using your hosting provider's DNS
* DNS resolution may not be quite as fast or reliable
* Your IP address becomes more visible to the internet and vulnerable to DDOS attacks
* Does not allow the root/naked domain to be routed through CloudFlare – it should be redirected to the "www" domain or another subdomain which has been enabled for CloudFlare
* Subdomains created via cPanel will work automatically
* RailGun automatically available for hosting partners that support it, no need to upgrade to business/enterprise plan.

**Comment by dfritsch** [comment]
Thanks for the idea! We are currently investigating how to add the option for users to sign up and use CloudFlare DNS through the cPanel extension and will definitely be adding this information as part of that process.
