### ISSUE TITLE
Subdomain not appearing in CloudFlare cPanel list

### ISSUE THREAD

**Issue by SimonEast** [cloudflare/CloudFlare-CPanel#21]
Here is an example whereby a subdomain created in cPanel does not appear in the CloudFlare settings page, and is not available for activation.  What might cause that?

### cPanel > Subdomains
![screenshot - 5 oct 2014 5_21_47 pm](https://cloud.githubusercontent.com/assets/813734/4517796/e01ff0d0-4c57-11e4-9a61-cb3c7a10ac50.png)

### cPanel > CloudFlare
![screenshot - 5 oct 2014 5_33_18 pm](https://cloud.githubusercontent.com/assets/813734/4517814/75e0f2a8-4c59-11e4-8a9b-403a8f1d4596.png)

**nsw.sbms.org.au** does not appear on the CloudFlare page.  Any suggestions as to why?

Here is the zone file for reference.

### cPanel > Advanced DNS Zone Editor
![screenshot - 5 oct 2014 5_34_13 pm](https://cloud.githubusercontent.com/assets/813734/4517816/9f7c4252-4c59-11e4-8f26-3ec2feeb4e82.png)

**Comment by HostOnNet** [comment]
Sub domains are A records in cpanel. Why nsw is a CNAME ? Manually added ?

**Comment by martijngonlag** [comment]
Hi Simon,

Only the FQDNs can be added to CloudFlare. So in this case, only sbms.org.au would only ever be added to CloudFlare. Sub-domains should be added by adding either an A or CNAME record along side the FQDN that you added to CloudFlare, and can be done through the DNS editor.

For future support requests please open a ticket by emailing partnersupport@cloudflare.com

**Comment by SimonEast** [comment]
Hi, sorry, just saw your reply.

I'm not sure I understand your response.  `sbms.org.au` is the FQDN that was added to CloudFlare through cPanel.  The various subdomains were also added through the cPanel "Subdomains" screen.  

My question was why would some subdomains be missing from the cPanel > CloudFlare screen?  I'm not sure that has been answered as yet.
