### ISSUE TITLE
cPanel mod_cloudflare and cPanel CloudFlare RailGun install scripts

### ISSUE THREAD

**Issue by tripflex** [cloudflare/CloudFlare-CPanel#44]
Just thought id post this here as an FYI:

This one is the actively updated version, includes mod_cloudflare setup, railgun config and installation, and more:
https://github.com/tripflex/cpsetup

This one I created years ago:
https://github.com/tripflex/cloudflarecp

I'll be adding the feature to recompile apache with mod_cloudflare using the latest build config in an upcoming release (for cpsetup).

**Comment by dfritsch** [comment]
Thanks for the FYI!
