### ISSUE TITLE
Cloudflare page on paper_lantern

### ISSUE THREAD

**Issue by lehels** [cloudflare/CloudFlare-CPanel#62]
We have detected that the Cloudflare page under cPanel with paper_lantern them is not showing up correctly: http://www.awesomescreenshot.com/0b5594vb48

cPanel version: 11.50
CF plugin version: 5.3.6

Can you please advise?

**Comment by martijngonlag** [comment]
Hi there,

Can you please open up a ticket by emailing partnersupport@cloudflare.com, and include the following information:

* Output from running cat /usr/local/cpanel/etc/cloudflare.json
* Output from running cat /usr/local/cpanel/etc/logs/error_log

This will ensure you receive the appropriate report!

**Comment by lehels** [comment]
I'm detecting that a new version has been made available since I've opened this issue, 5.3.8 - which apparently fixes the problem reported. :) The `cloudflare_update.sh` though has some bugs when going from 5.3.6 to 5.3.8 - which I'll report to that email address. Thanks much.
