### ISSUE TITLE
Not working with the latest version of WHM/cPanel.

### ISSUE THREAD

**Issue by juliocoliveira** [cloudflare/CloudFlare-CPanel#72]
The WHM was updated to 11.52.0 (build 21), Today i tried to use the cloudflare plugin on cPanel, but is not working when i click on the CloudFlare icon (/frontend/paper_lantern/cloudflare/index.html) It takes forever to load, I left there and 10 minutes later it was still loading.

**Comment by martijngonlag** [comment]
Please open a ticket containing the below information by emailing partnersupport@cloudflare.com.

* Contents of /usr/local/cpanel/etc/cloudflare.json
* Contents of /usr/local/cpanel/logs/error_log
* A HAR file capturing the issue loading the index
