### ISSUE TITLE
Is it possible to enable CloudFlare via cPanel if the domain's nameservers are managed externally?

### ISSUE THREAD

**Issue by SimonEast** [cloudflare/CloudFlare-CPanel#77]
In normal scenarios, the web host that serves the webpages and provides cPanel also manages the nameserver. This is not always the case, however.

What is required when a nameserver is managed externally?  After enabling CloudFlare optimization inside the cPanel plugin, is it simply a matter of adding the CNAME record manually to the external zone file?  ie...

    mydomain.com  CNAME  mydomain.com.cdn.cloudflare.net.

If so, how does CloudFlare actually know the IP address of the origin server - is CloudFlare somehow informed of this via the cPanel plugin?

**Comment by SimonEast** [comment]
Oh, I just noticed `cloudflare-resolve-to.example.com` mentioned in the README.

So would that mean that *both* these records need to be added to the external zone file?

    www.mydomain.com  CNAME  www.mydomain.com.cdn.cloudflare.net.
    cloudflare-resolve-to.www.mydomain.com  CNAME  myoriginserver.com

And similar for any additional subdomains...?

    subdomain.mydomain.com  CNAME  subdomain.mydomain.com.cdn.cloudflare.net.
    cloudflare-resolve-to.subdomain.mydomain.com  CNAME  subdomain.myoriginserver.com

And does it matter if the second record is a CNAME or A record?  Although CNAMEs are slower to resolve, they will be more likely to stay accurate if the host changes their IP address.

**Comment by jwineman** [comment]
Hi Simon,
You only need one `cloudflare-resolve-to` record so in your case the DNS record setup would look like the following:
```
www.mydomain.com  CNAME  www.mydomain.com.cdn.cloudflare.net.
subdomain.mydomain.com  CNAME  subdomain.mydomain.com.cdn.cloudflare.net.
cloudflare-resolve-to.mydomain.com  CNAME  myoriginserver.com
```
Also your `cloudflare-resolve-to` shouldn't be `www` specific.

FYI we try to keep Github Issues specific to bugs/features involving the Cpanel integration itself.  In the future please submit a ticket with CloudFlare Support (https://support.cloudflare.com/hc/en-us)

Thanks,
John

**Comment by SimonEast** [comment]
Thanks John.

The reason I posted it here is because it might be helpful if the plugin actually gave a couple of those instructions instead of leaving you with the impression that it should "just work". Even a simple link to a knowledgebase article would be great.

It's difficult to sometimes get support for issues like these because Cloudflare might say "go talk to your web host" and then the web host says "go talk to Cloudflare". Infinite loop. Had that happen before.

Anyway appreciate your helpful reply.

**Comment by jwineman** [comment]
I understand.  We're actually in the process of redesigning the CPanel plugin (as well as our other plugins) and one of the goals is to make all these things much more clear.  This is great feedback!
