### ISSUE TITLE
Updating the plugin

### ISSUE THREAD

**Issue by skechboy** [cloudflare/CloudFlare-CPanel#79]
Hello,

At start I assumed that the plugin is auto updating itself however when I've compared the github source with those in production and they were quite different. 

It would be really nice if we could find more documentation on how to update the plugin, in order to avoid problems with the clients that already have activated CloudFlare. 

Thanks

**Comment by jwineman** [comment]
Hi,

The plugin does auto update itself.  The installation/update scripts move and delete some files but the underlying application code should be the same.  Which version of the plugin are you running?  Which files do you see differences in?

Thanks,
John

**Comment by jwineman** [comment]
Please file a support ticket at CloudFlare.com if you need further assistance with this.
