### ISSUE TITLE
v5.3.11 not installing correctly on cpanel 56

### ISSUE THREAD

**Issue by momon** [cloudflare/CloudFlare-CPanel#80]
So just yesterday I installed on a few of our servers which were still on version 54.  They all installed without issues.  Today I went to install on one of our servers that had just updated to version 56 and it appears not to be working correctly.

There is no error on the install process but this definitely looks odd, when I log into any cpanel account there is a single icon installed mixed with other icons (not a category specific to cloudflare as per the other installs I've done).  There is also no /usr/local/cpanel/etc/cloudflare.json file setup.

Clicking on the one cloudflare icon brings up a broken design page which simply asks to login to a cloudflare account and there are no further options nor buttons unlike the version that installed on our other servers.

Also the install instructions appear to have changed since we now have to use the -k and -n parameters for they key and name and this isn't referenced in the documentation either.  So I am not sure if the new version is not yet fully published but I don't seem to be able to install the version 5 either since attempting to do that automatically downloads version 6 anyways.

**Comment by jwineman** [comment]
Hey,

Can you confirm your trying to install 5.3.11 and which cPanel theme you're using?

To give you some context we released 6.0.0 yesterday, the 5.x -> 6 upgrade process doesn't uninstall the 5.x version because we deprecated support for the x3 theme in 6 but still wanted people on older versions to be able to use the plugin.

**Comment by momon** [comment]
Thank you for the prompt reply, it is much appreciated.

I just checked on the servers I installed yesterday and you are right, I have 5.3.11 installed on those.  I don't see any specific instructions to install that version on this new server but I tried changing brand to v5 and follow the steps, it still forces the download to version 6.

I even tried installing from the local file (an archive of version 5 manually downloaded) and it still during install downloads version 6 and installs that (or tries to apparently).

It would be very helpful to me if you could provide specific instructions on how to install version 5.3 so I can keep all servers the same version (at least for now) but if that is no longer possible, then I can install version 6, however I have the issues I reported in my original post with it where it doesn't seem to install correctly and there is just one icon on the theme.

When I installed version 6 I tested it on the paper lantern theme (the latest from cpanel) but on this server I have both themes available (x3 and paper lantern) so can test either version on either theme as needed depending on which "working" install instructions you can provide that would lead to a successful install.

Thanks and I apologize if this is too confusing, I am just trying to give you all the information I have at hands right now.

**Comment by jwineman** [comment]
If you run the v5 uninstaller:

`et https://raw.githubusercontent.com/cloudflare/CloudFlare-CPanel/v5/cloudflare/installers/cloudflare.cpanelplugin && bash <(curl -s https://raw.githubusercontent.com/cloudflare/CloudFlare-CPanel/v5/cloudflare/uninstall_cf) && rm -f uninstall_cf`

And then install version 6 it should resolve the issues you were talking about.  

Version 5 allowed for "simple" or "extended" installation which varied the number of icons but version six now only supports "simple" where there is one CloudFlare icon.

I've started work on a version of 5.3 that doesn't automatically try to update to 6 but it wont be ready until some time next week.  Hopefully the v5 uninstall followed by a clean v6 install will work for you in the mean time.

**Comment by momon** [comment]
thank you.

So it sounds like there is no way to install version 5.3 right now?

I do not have version 5 installed, it never was (on this server).  I tried to install it but when I issue the install command it downloads version 6, not version 5.

So if I understand correctly and version 6 is supposed to have just 1 icon then maybe I had it installed correctly, however when you go into that icon things don't look very well.  Layout is messed up (mainly the div containing CF that overlaps the cpanel container and breaks things up on the paper lantern theme (if using the style that looks like x3 which is an option)

Additionally that content is not as intuitive as the one that was available in version 5 where you have more options to click through even before logging in.

is there any way to get the version 5 installed right now?

**Comment by jwineman** [comment]
Well I haven't tested but I think 5.3.11 should install fine but the cron job will try to upgrade to 6.0.0 so in theory if you remove the cron job after installing 5.3.11 you should be fine.  

The root cause for you (I think) is that the 5.3.11 > 6 upgrade process intentionally doesn't uninstall the 5.3.11 icons on X3 so they continue to work.  Can you post a screenshot of the way your icons look?

**Comment by momon** [comment]
Well, no, 5.3.11 is not installing at all, here is what I mean:

I have hidden my key and name:

root@kiwi [~]# bash <(curl -s https://raw.githubusercontent.com/cloudflare/CloudFlare-CPanel/v5/cloudflare.install.sh) xxxxxxx 'xxxxxx' -v
Starting CloudFlare CPanel Installation...

Downloading and unpacking latest version v6.0.0...
Finalizing install...
./install_cf: line 14: cd: ../CloudFlare-CPanel*: No such file or directory
Cleaning up
Verify Host Name:
cat: /usr/local/cpanel/etc/cloudflare.json: No such file or directory
root@kiwi [~]#

As you can see, when I try to install v5, it downloads v6 for some reason and does not install.

**Comment by jwineman** [comment]
Ah my mistake, I understand now.  Fixed in c08da7a6ecda1680feec3952f740cbd978ec272a on the v5 branch.  Please try again.

**Comment by momon** [comment]
Yup, that was it.  Thanks!

**Comment by jwineman** [comment]
Do you need anything else?

**Comment by momon** [comment]
No that's all thank you.
