### ISSUE TITLE
Auto update does not work

### ISSUE THREAD

**Issue by pinhao** [cloudflare/CloudFlare-CPanel#89]
The new_version variable is declared in upper case but is used in the if statement in lower case, also the curl request is just outputting to stdout and not interpreting the code.

**Comment by jwineman** [comment]
Good catch - thank you!  We'll get a fix pushed out ASAP.

**Comment by jwineman** [comment]
Fixed in caffcac0a80d734e1989cf38a5210858a6cb6047, should be a part of the 6.0.2 release.
