### ISSUE TITLE
Domain inactive

### ISSUE THREAD

**Issue by bettinz** [cloudflare/CloudFlare-CPanel#93]
Hello, I'm using cpanel with paper lantern 11.54 and cloudflare plugin 6.0.2
The problem is that when I'm trying to enable a domain, the domain is activated on cloudflare (and dns updated) but in cpanel interface I still see the domain disabled (cloudflare plan is empty, zone type is empty and use cloudflare->inactive). The strange thing is the domain is active if I'm login in cloudflare.com.

**Comment by jwineman** [comment]
Hi,

Can you please [open up a support](https://support.cloudflare.com/hc/en-us/requests/new) ticket after doing the following:

1. Edit `/usr/local/cpanel/base/frontend/paper_lantern/cloudflare/config.js` and change
`debug` from `false` to `true`.
2. In the terminal run `tail -1000f /usr/local/cpanel/logs/error_log`
3. Try to enable the domain and copy the logs that it outputs into the support ticket.

Thanks,
John
