### ISSUE TITLE
Cloudflare installation issue - no such file or directory

### ISSUE THREAD

**Issue by wci-aw** [cloudflare/CloudFlare-CPanel#94]
Dear support team,

we tried to install a cpanel cloudflare addon but the install routine is interrupted before finalization.
> May find this screenshot helpful - [link removed]

We tried to use this guide for installation (https://www.dropbox.com/s/riwd4bgoyumqz9p/cloudflare-cpanel-installation-activation-guide.pdf?dl=0) but cannot get it to run.

I also reported the failure on cpanel support [https://tickets.cpanel.net/review/msg.cgi?ticketid=7566529](url) and the suggested me to inform you with this advice:
-----
> As the cloudflare plugin is a third party application and is not part of cPanel, or the basic configuration of bundled software, I can offer advice as a courtesy but will not be able to take actions to resolve the issue on your behalf.

> It appears the script in question attempts to use a relative path directory for the cd command that incorrectly references the path name:

> [07:55:32 server01 root@7566529 /usr/local/cpanel/cloudflare-CloudFlare-CPanel-5b8bd3a]cPs# sed -n 14p ./cloudflare/install_cf
(cd ../CloudFlare-CPanel* && mv * ../ && ../cloudflare.install.sh -k $HOST_KEY -n '${FORMAL_NAME}')

> My suggestion would be to use an absolute path "/usr/local/cpanel/cloudflare-CloudFlare-CPanel-5b8bd3a" rather than "../CloudFlare-CPanel*" to see if this resolves the issue.

> Please note this suggestion could result in unexpected behavior and I would suggest contacting the scripts developer or maintainer before making this modification on a production system.
-------

Please help & advice how to proceed further to enable a proper installation on our dedicated server.

Thanks in advance. Alex

**Comment by jwineman** [comment]
Hi Alex,

The document you referenced in DropBox is the version 5 installer.  The version 6 installer is slightly different, with instructions on our [README](https://github.com/cloudflare/CloudFlare-CPanel/#cloudflare-cpanel-quick-installation-instructions).  Try that command instead and let us know if it works!

Thanks,
John

**Comment by wci-aw** [comment]
Hi John, 
thanks for reply. 

I/we will test on Monday and let you know. 
THANKS and have a great weekend.

Alex

**Comment by jwineman** [comment]
Hi Alex,

Any update on this?

Thanks,
John

**Comment by wci-aw** [comment]
Hi John, 
we still have issues not beeing able to install your software. I ask my developer to state the problem here. It seems that there is a system incompatibality. We use 

- as Hardware:
Intel Core i7-3930
2x HDD 3,0 TB SATA
8x RAM 8192 MB DDR3

- as Software:
we use linux and 
CENTOS 7.2 x86_64 standard  
cpanel vers.  56.0.22 
please check our [php info](https://www.worldcheckin.com/phpinfo.php)

**Comment by jwineman** [comment]
Hey Alex,

The plugin is compatible with cPanel 56 and your hardware.  Please email partnersupport@cloudflare.com with the following information and we'll help you debug further.

-The exact command you're running to install the script.
-The error you're getting.

Thanks,
John

**Comment by ashokarun** [comment]
Did you try to change the path from relative to absolute in install_cf file?

[Edit install_cf](https://crybit.com/install-cloudflare-plugin-on-cpanel/)
